// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Tools.TeamMate.Foundation.Resources
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Tools.TeamMate.Foundation.Resources.ResourceStrings", typeof(ResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ago.
        /// </summary>
        internal static string Ago {
            get {
                return ResourceManager.GetString("Ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string DayAndDate {
            get {
                return ResourceManager.GetString("DayAndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a day.
        /// </summary>
        internal static string ElapsedTimeADay {
            get {
                return ResourceManager.GetString("ElapsedTimeADay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a minute.
        /// </summary>
        internal static string ElapsedTimeAMinute {
            get {
                return ResourceManager.GetString("ElapsedTimeAMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a month.
        /// </summary>
        internal static string ElapsedTimeAMonth {
            get {
                return ResourceManager.GetString("ElapsedTimeAMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an hour.
        /// </summary>
        internal static string ElapsedTimeAnHour {
            get {
                return ResourceManager.GetString("ElapsedTimeAnHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a week.
        /// </summary>
        internal static string ElapsedTimeAWeek {
            get {
                return ResourceManager.GetString("ElapsedTimeAWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a year.
        /// </summary>
        internal static string ElapsedTimeAYear {
            get {
                return ResourceManager.GetString("ElapsedTimeAYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days.
        /// </summary>
        internal static string ElapsedTimeDays {
            get {
                return ResourceManager.GetString("ElapsedTimeDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours.
        /// </summary>
        internal static string ElapsedTimeHours {
            get {
                return ResourceManager.GetString("ElapsedTimeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less than a minute.
        /// </summary>
        internal static string ElapsedTimeLessThanMinute {
            get {
                return ResourceManager.GetString("ElapsedTimeLessThanMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes.
        /// </summary>
        internal static string ElapsedTimeMinutes {
            get {
                return ResourceManager.GetString("ElapsedTimeMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} months.
        /// </summary>
        internal static string ElapsedTimeMonths {
            get {
                return ResourceManager.GetString("ElapsedTimeMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} weeks.
        /// </summary>
        internal static string ElapsedTimeWeeks {
            get {
                return ResourceManager.GetString("ElapsedTimeWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years.
        /// </summary>
        internal static string ElapsedTimeYears {
            get {
                return ResourceManager.GetString("ElapsedTimeYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on {0}.
        /// </summary>
        internal static string OnDate {
            get {
                return ResourceManager.GetString("OnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} at {1}.
        /// </summary>
        internal static string TimeStampDayAt {
            get {
                return ResourceManager.GetString("TimeStampDayAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}.
        /// </summary>
        internal static string TimeStampFullDate {
            get {
                return ResourceManager.GetString("TimeStampFullDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today at {0}.
        /// </summary>
        internal static string TimeStampTodayAt {
            get {
                return ResourceManager.GetString("TimeStampTodayAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday at {0}.
        /// </summary>
        internal static string TimeStampYesterdayAt {
            get {
                return ResourceManager.GetString("TimeStampYesterdayAt", resourceCulture);
            }
        }
    }
}
