// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard
{


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CodeReviewQuery", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.CodeFlow.ServiceModel")]
    [System.SerializableAttribute()]
    public partial class CodeReviewQuery : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] AuthorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreatedAfterDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreatedBeforeDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ProjectsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.CodeReviewStatus[] ReviewStatusesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ReviewersField;
        
        private string UserAgentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastUpdatedAfterDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastUpdatedBeforeDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageIndexField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Authors {
            get {
                return this.AuthorsField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorsField, value) != true)) {
                    this.AuthorsField = value;
                    this.RaisePropertyChanged("Authors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedAfterDate {
            get {
                return this.CreatedAfterDateField;
            }
            set {
                if ((this.CreatedAfterDateField.Equals(value) != true)) {
                    this.CreatedAfterDateField = value;
                    this.RaisePropertyChanged("CreatedAfterDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedBeforeDate {
            get {
                return this.CreatedBeforeDateField;
            }
            set {
                if ((this.CreatedBeforeDateField.Equals(value) != true)) {
                    this.CreatedBeforeDateField = value;
                    this.RaisePropertyChanged("CreatedBeforeDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxResults {
            get {
                return this.MaxResultsField;
            }
            set {
                if ((this.MaxResultsField.Equals(value) != true)) {
                    this.MaxResultsField = value;
                    this.RaisePropertyChanged("MaxResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Projects {
            get {
                return this.ProjectsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectsField, value) != true)) {
                    this.ProjectsField = value;
                    this.RaisePropertyChanged("Projects");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.CodeReviewStatus[] ReviewStatuses {
            get {
                return this.ReviewStatusesField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewStatusesField, value) != true)) {
                    this.ReviewStatusesField = value;
                    this.RaisePropertyChanged("ReviewStatuses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Reviewers {
            get {
                return this.ReviewersField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewersField, value) != true)) {
                    this.ReviewersField = value;
                    this.RaisePropertyChanged("Reviewers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UserAgent {
            get {
                return this.UserAgentField;
            }
            set {
                if ((object.ReferenceEquals(this.UserAgentField, value) != true)) {
                    this.UserAgentField = value;
                    this.RaisePropertyChanged("UserAgent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.Nullable<System.DateTime> LastUpdatedAfterDate {
            get {
                return this.LastUpdatedAfterDateField;
            }
            set {
                if ((this.LastUpdatedAfterDateField.Equals(value) != true)) {
                    this.LastUpdatedAfterDateField = value;
                    this.RaisePropertyChanged("LastUpdatedAfterDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.Nullable<System.DateTime> LastUpdatedBeforeDate {
            get {
                return this.LastUpdatedBeforeDateField;
            }
            set {
                if ((this.LastUpdatedBeforeDateField.Equals(value) != true)) {
                    this.LastUpdatedBeforeDateField = value;
                    this.RaisePropertyChanged("LastUpdatedBeforeDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int PageIndex {
            get {
                return this.PageIndexField;
            }
            set {
                if ((this.PageIndexField.Equals(value) != true)) {
                    this.PageIndexField = value;
                    this.RaisePropertyChanged("PageIndex");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CodeReviewStatus", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.CodeFlow.ServiceModel")]
    public enum CodeReviewStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Created = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Completed = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Aborted = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Expired = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CodeReviewQueryResult", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.CodeFlow.ServiceModel")]
    [System.SerializableAttribute()]
    public partial class CodeReviewQueryResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.TimeSpan QueryDurationField;
        
        private Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.CodeReviewSummary[] ReviewsField;
        
        private int TotalResultsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.TimeSpan QueryDuration {
            get {
                return this.QueryDurationField;
            }
            set {
                if ((this.QueryDurationField.Equals(value) != true)) {
                    this.QueryDurationField = value;
                    this.RaisePropertyChanged("QueryDuration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.CodeReviewSummary[] Reviews {
            get {
                return this.ReviewsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewsField, value) != true)) {
                    this.ReviewsField = value;
                    this.RaisePropertyChanged("Reviews");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TotalResults {
            get {
                return this.TotalResultsField;
            }
            set {
                if ((this.TotalResultsField.Equals(value) != true)) {
                    this.TotalResultsField = value;
                    this.RaisePropertyChanged("TotalResults");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CodeReviewSummary", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.CodeFlow.ServiceModel")]
    [System.SerializableAttribute()]
    public partial class CodeReviewSummary : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AuthorLoginField;
        
        private string KeyField;
        
        private System.DateTime LastUpdatedOnField;
        
        private string NameField;
        
        private string ProjectShortNameField;
        
        private int RevisionField;
        
        private Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.CodeReviewStatus StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.Author AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CompletedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IterationCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.Reviewer[] ReviewersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.WorkItem[] WorkItemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string AuthorLogin {
            get {
                return this.AuthorLoginField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorLoginField, value) != true)) {
                    this.AuthorLoginField = value;
                    this.RaisePropertyChanged("AuthorLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime LastUpdatedOn {
            get {
                return this.LastUpdatedOnField;
            }
            set {
                if ((this.LastUpdatedOnField.Equals(value) != true)) {
                    this.LastUpdatedOnField = value;
                    this.RaisePropertyChanged("LastUpdatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ProjectShortName {
            get {
                return this.ProjectShortNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectShortNameField, value) != true)) {
                    this.ProjectShortNameField = value;
                    this.RaisePropertyChanged("ProjectShortName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Revision {
            get {
                return this.RevisionField;
            }
            set {
                if ((this.RevisionField.Equals(value) != true)) {
                    this.RevisionField = value;
                    this.RaisePropertyChanged("Revision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.CodeReviewStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.Author Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.DateTime CompletedOn {
            get {
                return this.CompletedOnField;
            }
            set {
                if ((this.CompletedOnField.Equals(value) != true)) {
                    this.CompletedOnField = value;
                    this.RaisePropertyChanged("CompletedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.DateTime CreatedOn {
            get {
                return this.CreatedOnField;
            }
            set {
                if ((this.CreatedOnField.Equals(value) != true)) {
                    this.CreatedOnField = value;
                    this.RaisePropertyChanged("CreatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int IterationCount {
            get {
                return this.IterationCountField;
            }
            set {
                if ((this.IterationCountField.Equals(value) != true)) {
                    this.IterationCountField = value;
                    this.RaisePropertyChanged("IterationCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.Reviewer[] Reviewers {
            get {
                return this.ReviewersField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewersField, value) != true)) {
                    this.ReviewersField = value;
                    this.RaisePropertyChanged("Reviewers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.WorkItem[] WorkItems {
            get {
                return this.WorkItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkItemsField, value) != true)) {
                    this.WorkItemsField = value;
                    this.RaisePropertyChanged("WorkItems");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Author", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.CodeFlow.ServiceModel")]
    [System.SerializableAttribute()]
    public partial class Author : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DisplayNameField;
        
        private string EmailAddressField;
        
        private System.DateTime LastUpdatedOnField;
        
        private string NameField;
        
        private Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.AuthorStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime LastUpdatedOn {
            get {
                return this.LastUpdatedOnField;
            }
            set {
                if ((this.LastUpdatedOnField.Equals(value) != true)) {
                    this.LastUpdatedOnField = value;
                    this.RaisePropertyChanged("LastUpdatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.AuthorStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reviewer", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.CodeFlow.ServiceModel")]
    [System.SerializableAttribute()]
    public partial class Reviewer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DisplayNameField;
        
        private string EmailAddressField;
        
        private System.DateTime LastUpdatedOnField;
        
        private string NameField;
        
        private bool RequiredField;
        
        private Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.ReviewerStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime LastUpdatedOn {
            get {
                return this.LastUpdatedOnField;
            }
            set {
                if ((this.LastUpdatedOnField.Equals(value) != true)) {
                    this.LastUpdatedOnField = value;
                    this.RaisePropertyChanged("LastUpdatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Required {
            get {
                return this.RequiredField;
            }
            set {
                if ((this.RequiredField.Equals(value) != true)) {
                    this.RequiredField = value;
                    this.RaisePropertyChanged("Required");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.ReviewerStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkItem", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.CodeFlow.ServiceModel")]
    [System.SerializableAttribute()]
    public partial class WorkItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string idField;
        
        private string titleField;
        
        private string typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Uri uriField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Uri uri {
            get {
                return this.uriField;
            }
            set {
                if ((object.ReferenceEquals(this.uriField, value) != true)) {
                    this.uriField = value;
                    this.RaisePropertyChanged("uri");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthorStatus", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.CodeFlow.ServiceModel")]
    public enum AuthorStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Preparing = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Waiting = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Working = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Completed = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReviewerStatus", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.CodeFlow.ServiceModel")]
    public enum ReviewerStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotStarted = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Started = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reviewing = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Waiting = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SignedOff = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InviteOnly = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Declined = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryReviewSummariesResult", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.CodeFlow.ServiceModel")]
    [System.SerializableAttribute()]
    public partial class QueryReviewSummariesResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.TimeSpan QueryDurationField;
        
        private Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.CodeReviewSummary[] ReviewsField;
        
        private int TotalResultsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.TimeSpan QueryDuration {
            get {
                return this.QueryDurationField;
            }
            set {
                if ((this.QueryDurationField.Equals(value) != true)) {
                    this.QueryDurationField = value;
                    this.RaisePropertyChanged("QueryDuration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.CodeReviewSummary[] Reviews {
            get {
                return this.ReviewsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewsField, value) != true)) {
                    this.ReviewsField = value;
                    this.RaisePropertyChanged("Reviews");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TotalResults {
            get {
                return this.TotalResultsField;
            }
            set {
                if ((this.TotalResultsField.Equals(value) != true)) {
                    this.TotalResultsField = value;
                    this.RaisePropertyChanged("TotalResults");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.CodeFlow.ServiceModel")]
    [System.SerializableAttribute()]
    public partial class ServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryReviewIdsResult", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.CodeFlow.ServiceModel")]
    [System.SerializableAttribute()]
    public partial class QueryReviewIdsResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.TimeSpan QueryDurationField;
        
        private string[] ReviewsField;
        
        private int TotalResultsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.TimeSpan QueryDuration {
            get {
                return this.QueryDurationField;
            }
            set {
                if ((this.QueryDurationField.Equals(value) != true)) {
                    this.QueryDurationField = value;
                    this.RaisePropertyChanged("QueryDuration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string[] Reviews {
            get {
                return this.ReviewsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewsField, value) != true)) {
                    this.ReviewsField = value;
                    this.RaisePropertyChanged("Reviews");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TotalResults {
            get {
                return this.TotalResultsField;
            }
            set {
                if ((this.TotalResultsField.Equals(value) != true)) {
                    this.TotalResultsField = value;
                    this.RaisePropertyChanged("TotalResults");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CodeFlow.Dashboard.IReviewDashboardService")]
    public interface IReviewDashboardService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewDashboardService/Query", ReplyAction="http://tempuri.org/IReviewDashboardService/QueryResponse")]
        Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.CodeReviewQueryResult Query([System.ServiceModel.MessageParameterAttribute(Name="query")] Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.CodeReviewQuery query1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewDashboardService/Query", ReplyAction="http://tempuri.org/IReviewDashboardService/QueryResponse")]
        System.Threading.Tasks.Task<Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.CodeReviewQueryResult> QueryAsync(Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.CodeReviewQuery query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewDashboardService/QueryReviewSummaries", ReplyAction="http://tempuri.org/IReviewDashboardService/QueryReviewSummariesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.ServiceFault), Action="http://tempuri.org/IReviewDashboardService/QueryReviewSummariesServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.CodeFlow.ServiceModel")]
        Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.QueryReviewSummariesResult QueryReviewSummaries(Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.CodeReviewQuery query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewDashboardService/QueryReviewSummaries", ReplyAction="http://tempuri.org/IReviewDashboardService/QueryReviewSummariesResponse")]
        System.Threading.Tasks.Task<Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.QueryReviewSummariesResult> QueryReviewSummariesAsync(Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.CodeReviewQuery query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewDashboardService/QueryReviewIds", ReplyAction="http://tempuri.org/IReviewDashboardService/QueryReviewIdsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.ServiceFault), Action="http://tempuri.org/IReviewDashboardService/QueryReviewIdsServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.CodeFlow.ServiceModel")]
        Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.QueryReviewIdsResult QueryReviewIds(Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.CodeReviewQuery query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewDashboardService/QueryReviewIds", ReplyAction="http://tempuri.org/IReviewDashboardService/QueryReviewIdsResponse")]
        System.Threading.Tasks.Task<Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.QueryReviewIdsResult> QueryReviewIdsAsync(Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.CodeReviewQuery query);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReviewDashboardServiceChannel : Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.IReviewDashboardService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReviewDashboardServiceClient : System.ServiceModel.ClientBase<Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.IReviewDashboardService>, Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.IReviewDashboardService {
        
        public ReviewDashboardServiceClient() {
        }
        
        public ReviewDashboardServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReviewDashboardServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReviewDashboardServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReviewDashboardServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.CodeReviewQueryResult Query(Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.CodeReviewQuery query1) {
            return base.Channel.Query(query1);
        }
        
        public System.Threading.Tasks.Task<Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.CodeReviewQueryResult> QueryAsync(Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.CodeReviewQuery query) {
            return base.Channel.QueryAsync(query);
        }
        
        public Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.QueryReviewSummariesResult QueryReviewSummaries(Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.CodeReviewQuery query) {
            return base.Channel.QueryReviewSummaries(query);
        }
        
        public System.Threading.Tasks.Task<Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.QueryReviewSummariesResult> QueryReviewSummariesAsync(Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.CodeReviewQuery query) {
            return base.Channel.QueryReviewSummariesAsync(query);
        }
        
        public Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.QueryReviewIdsResult QueryReviewIds(Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.CodeReviewQuery query) {
            return base.Channel.QueryReviewIds(query);
        }
        
        public System.Threading.Tasks.Task<Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.QueryReviewIdsResult> QueryReviewIdsAsync(Microsoft.Tools.TeamMate.Platform.CodeFlow.Dashboard.CodeReviewQuery query) {
            return base.Channel.QueryReviewIdsAsync(query);
        }
    }
}
